services:
  app:
    build: .
    ports:
      - "8051:8051"
    volumes:
      - ./src/.env:/app/src/.env
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - OMP_NUM_THREADS=1
      - NUMEXPR_NUM_THREADS=1
      - TOKENIZERS_PARALLELISM=false
    restart: always
