[project]
name = "nerdbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "networkx>=3.4.2",
    "pandas>=2.2.3",
    "pip>=25.0",
    "plotly>=5.24.1",
    "pymongo>=4.10.1",
    "pynvim>=0.5.2",
    "python-dotenv>=1.0.1",
    "scipy>=1.15.1",
    "streamlit>=1.41.1",
    "transformers>=4.50.3",
]
