[project]
name = "nerdbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bertopic>=0.17.0",
    "loguru>=0.7.3",
    "matplotlib>=3.10.1",
    "networkx>=3.4.2",
    "numba>=0.61.0",
    "pandas>=2.2.3",
    "pip>=25.0",
    "plotly>=5.24.1",
    "pymongo>=4.10.1",
    "pynvim>=0.5.2",
    "pytest>=8.3.5",
    "python-dotenv>=1.0.1",
    "scikit-learn>=1.6.1",
    "scipy>=1.15.1",
    "sentence-transformers>=4.0.2",
    "streamlit>=1.41.1",
    "transformers>=4.50.3",
    "typing>=3.10.0.0",
]
