[project]
name = "nerdbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bertopic>=0.17.0",
    "clang>=20.1.0",
    "loguru>=0.7.3",
    "matplotlib>=3.10.1",
    "networkx>=3.4.2",
    "numba>=0.61.0",
    "pandas>=2.2.3",
    "pip>=25.0",
    "plotly>=5.24.1",
    "pymongo>=4.10.1",
    "pynvim>=0.5.2",
    "pytest>=8.3.5",
    "python-dotenv>=1.0.1",
    "scikit-learn>=1.6.1",
    "scipy>=1.15.1",
    "sentence-transformers>=4.0.2",
    "streamlit>=1.41.1",
    "transformers>=4.50.3",
    "typing>=3.10.0.0",
    "watchdog>=6.0.0",
]

[tool.basedpyright]
ignore = ['*']
typeCheckingMode = "standard"
reportMissingImports = "error"
reportMissingTypeStubs = "information"
reportArgumentType = "information"
reportCallIssue = "information"

[tool.ruff]
fix = true
line-length = 88
exclude = ["*/.venv"]
[tool.ruff.lint]
select = [
    "B", # Errors and bad practices (from flake8-bugbear).
    # "D", # Docstrings, to check their presence and format.
    "E",   # Style errors, alignment, and code conventions.
    "F",   # Code errors (equivalent to flake8, detects critical issues).
    "I",   # Imports (reordering, duplicates, and conventions).
    "Q",   # Improper SQL queries (if applicable to your project).
    "S",   # Security (detects common vulnerabilities).
    "NPY", # Numpy (detects common issues with numpy)
    "PD",  # Pandas (detects common issues with pandas).
]

ignore = ["S101", "PD901"]
